# If the cloud environment variable ${PORT} exists, use it. Otherwise, default to 8080.
server.port=${PORT:8080}

langchain4j.open-ai.chat-model.base-url=https://api.groq.com/openai/v1
langchain4j.open-ai.chat-model.api-key=${GROQ_API_KEY}
langchain4j.open-ai.chat-model.model-name=llama3-8b-8192
langchain4j.open-ai.chat-model.temperature=0.7